using NovaEngine.Common.Windows.Api;
using NovaEngine.Common.Windows.Native;
using NovaEngine.IO;

namespace NovaEngine.Common.Windows;

/// <summary>Contains useful miscellaneous methods for the Win32 platform.</summary>
public static class Win32Utilities
{
    /// <summary>Converts a <see cref="VirtualKey"/> to a <see cref="Key"/>.</summary>
    /// <param name="virtualKey">The virtual key to convert.</param>
    /// <param name="isE0BitSet">Whether the <see cref="RawInputKeyboardDataFlags.E0"/> bit is set on the keyboard event flags.</param>
    /// <param name="makeCode">The make code.</param>
    /// <returns>The converted <paramref name="virtualKey"/>.</returns>
    public static Key ConvertVirtualKey(VirtualKey virtualKey, bool isE0BitSet, ushort makeCode)
    {
        return (virtualKey, isE0BitSet, makeCode) switch
        {
            (VirtualKey.Back, _, _) => Key.BackSpace,
            (VirtualKey.Tab, _, _) => Key.Tab,
            (VirtualKey.Return, _, _) => Key.Enter,
            (VirtualKey.Shift, _, User32.ShiftRight) => Key.RightShift,
            (VirtualKey.Shift, _, _) => Key.LeftShift,
            (VirtualKey.Control, true, _) => Key.RightControl,
            (VirtualKey.Control, false, _) => Key.LeftControl,
            (VirtualKey.Menu, true, _) => Key.RightAlt,
            (VirtualKey.Menu, false, _) => Key.LeftAlt,
            (VirtualKey.Pause, _, _) => Key.PauseBreak,
            (VirtualKey.Capital, _, _) => Key.CapsLock,
            (VirtualKey.Escape, _, _) => Key.Escape,
            (VirtualKey.Space, _, _) => Key.Space,
            (VirtualKey.Prior, _, _) => Key.PageUp,
            (VirtualKey.Next, _, _) => Key.PageDown,
            (VirtualKey.End, _, _) => Key.End,
            (VirtualKey.Home, _, _) => Key.Home,
            (VirtualKey.Left, _, _) => Key.LeftArrow,
            (VirtualKey.Up, _, _) => Key.UpArrow,
            (VirtualKey.Right, _, _) => Key.RightArrow,
            (VirtualKey.Down, _, _) => Key.DownArrow,
            (VirtualKey.Snapshot, _, _) => Key.PrintScreen,
            (VirtualKey.Insert, _, _) => Key.Insert,
            (VirtualKey.Delete, _, _) => Key.Delete,
            (VirtualKey.Number0, _, _) => Key.Number0,
            (VirtualKey.Number1, _, _) => Key.Number1,
            (VirtualKey.Number2, _, _) => Key.Number2,
            (VirtualKey.Number3, _, _) => Key.Number3,
            (VirtualKey.Number4, _, _) => Key.Number4,
            (VirtualKey.Number5, _, _) => Key.Number5,
            (VirtualKey.Number6, _, _) => Key.Number6,
            (VirtualKey.Number7, _, _) => Key.Number7,
            (VirtualKey.Number8, _, _) => Key.Number8,
            (VirtualKey.Number9, _, _) => Key.Number9,
            (VirtualKey.A, _, _) => Key.A,
            (VirtualKey.B, _, _) => Key.B,
            (VirtualKey.C, _, _) => Key.C,
            (VirtualKey.D, _, _) => Key.D,
            (VirtualKey.E, _, _) => Key.E,
            (VirtualKey.F, _, _) => Key.F,
            (VirtualKey.G, _, _) => Key.G,
            (VirtualKey.H, _, _) => Key.H,
            (VirtualKey.I, _, _) => Key.I,
            (VirtualKey.J, _, _) => Key.J,
            (VirtualKey.K, _, _) => Key.K,
            (VirtualKey.L, _, _) => Key.L,
            (VirtualKey.M, _, _) => Key.M,
            (VirtualKey.N, _, _) => Key.N,
            (VirtualKey.O, _, _) => Key.O,
            (VirtualKey.P, _, _) => Key.P,
            (VirtualKey.Q, _, _) => Key.Q,
            (VirtualKey.R, _, _) => Key.R,
            (VirtualKey.S, _, _) => Key.S,
            (VirtualKey.T, _, _) => Key.T,
            (VirtualKey.U, _, _) => Key.U,
            (VirtualKey.V, _, _) => Key.V,
            (VirtualKey.W, _, _) => Key.W,
            (VirtualKey.X, _, _) => Key.X,
            (VirtualKey.Y, _, _) => Key.Y,
            (VirtualKey.Z, _, _) => Key.Z,
            (VirtualKey.LWin, _, _) => Key.LeftWindows,
            (VirtualKey.RWin, _, _) => Key.RightWindows,
            (VirtualKey.Apps, _, _) => Key.Apps,
            (VirtualKey.Numpad0, _, _) => Key.Numpad0,
            (VirtualKey.Numpad1, _, _) => Key.Numpad1,
            (VirtualKey.Numpad2, _, _) => Key.Numpad2,
            (VirtualKey.Numpad3, _, _) => Key.Numpad3,
            (VirtualKey.Numpad4, _, _) => Key.Numpad4,
            (VirtualKey.Numpad5, _, _) => Key.Numpad5,
            (VirtualKey.Numpad6, _, _) => Key.Numpad6,
            (VirtualKey.Numpad7, _, _) => Key.Numpad7,
            (VirtualKey.Numpad8, _, _) => Key.Numpad8,
            (VirtualKey.Numpad9, _, _) => Key.Numpad9,
            (VirtualKey.Multiply, _, _) => Key.NumpadMultiply,
            (VirtualKey.Add, _, _) => Key.NumpadAdd,
            (VirtualKey.Subtract, _, _) => Key.NumpadSubtract,
            (VirtualKey.Decimal, _, _) => Key.NumpadDecimal,
            (VirtualKey.Divide, _, _) => Key.NumpadDivide,
            (VirtualKey.F1, _, _) => Key.F1,
            (VirtualKey.F2, _, _) => Key.F2,
            (VirtualKey.F3, _, _) => Key.F3,
            (VirtualKey.F4, _, _) => Key.F4,
            (VirtualKey.F5, _, _) => Key.F5,
            (VirtualKey.F6, _, _) => Key.F6,
            (VirtualKey.F7, _, _) => Key.F7,
            (VirtualKey.F8, _, _) => Key.F8,
            (VirtualKey.F9, _, _) => Key.F9,
            (VirtualKey.F10, _, _) => Key.F10,
            (VirtualKey.F11, _, _) => Key.F11,
            (VirtualKey.F12, _, _) => Key.F12,
            (VirtualKey.F13, _, _) => Key.F13,
            (VirtualKey.F14, _, _) => Key.F14,
            (VirtualKey.F15, _, _) => Key.F15,
            (VirtualKey.F16, _, _) => Key.F16,
            (VirtualKey.F17, _, _) => Key.F17,
            (VirtualKey.F18, _, _) => Key.F18,
            (VirtualKey.F19, _, _) => Key.F19,
            (VirtualKey.F20, _, _) => Key.F20,
            (VirtualKey.F21, _, _) => Key.F21,
            (VirtualKey.F22, _, _) => Key.F22,
            (VirtualKey.F23, _, _) => Key.F23,
            (VirtualKey.F24, _, _) => Key.F24,
            (VirtualKey.NumLock, _, _) => Key.NumLock,
            (VirtualKey.Scroll, _, _) => Key.ScrollLock,
            (VirtualKey.LShift, _, _) => Key.LeftShift,
            (VirtualKey.RShift, _, _) => Key.RightShift,
            (VirtualKey.LControl, _, _) => Key.LeftControl,
            (VirtualKey.RControl, _, _) => Key.RightControl,
            (VirtualKey.LMenu, _, _) => Key.LeftAlt,
            (VirtualKey.RMenu, _, _) => Key.RightAlt,
            (VirtualKey.VolumeMute, _, _) => Key.VolumeMute,
            (VirtualKey.VolumeDown, _, _) => Key.VolumeDown,
            (VirtualKey.VolumeUp, _, _) => Key.VolumeUp,
            (VirtualKey.MediaNextTrack, _, _) => Key.MediaNextTrack,
            (VirtualKey.MediaPrevTrack, _, _) => Key.MediaPrevTrack,
            (VirtualKey.MediaStop, _, _) => Key.MediaStop,
            (VirtualKey.MediaPlayPause, _, _) => Key.MediaPlayPause,
            (VirtualKey.OEM_Plus, _, _) => Key.OEM_Plus,
            (VirtualKey.OEM_Comma, _, _) => Key.OEM_Comma,
            (VirtualKey.OEM_Minus, _, _) => Key.OEM_Minus,
            (VirtualKey.OEM_Period, _, _) => Key.OEM_Period,
            (VirtualKey.OEM_1, _, _) => Key.OEM_1,
            (VirtualKey.OEM_2, _, _) => Key.OEM_2,
            (VirtualKey.OEM_3, _, _) => Key.OEM_3,
            (VirtualKey.OEM_4, _, _) => Key.OEM_4,
            (VirtualKey.OEM_5, _, _) => Key.OEM_5,
            (VirtualKey.OEM_6, _, _) => Key.OEM_6,
            (VirtualKey.OEM_7, _, _) => Key.OEM_7,
            (VirtualKey.OEM_8, _, _) => Key.OEM_8,
            _ => Key.Unknown
        };
    }
}
